import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  contener:{
    flex:1,
    justifyContent:'center',
    alignItems:"center",
    padding:8,
    width:"100%",
    backgroundColor:"#fff",
},
  contener2:{
    flex:1,
    justifyContent:'center',
    alignItems:'center',
    padding:10,
    width:'100%',
},
tituloPric:{
    fontSize:45,
    fontWeight:'600',
    textAlign:'center',
    fontFamily:"Arial",
    color:"#23238E",
},
btn:{
  textAlign:"center",
  padding:10,
  width:130,
  height:45,
  margin:"auto",
  borderStyle:'solid',
  borderColor:'#23238E',
  borderWidth:1,
  borderRadius:10,
  backgroundColor:'#4D4DFF'
},
btn2:{
  textAlign:"center",
  padding:10,
  width:90,
  height:45,
  margin:'auto',
  borderStyle:'solid',
  borderWidth:1,
  borderColor:'#000',
  borderRadius:10,
  backgroundColor:'#fff',
  color:"#000",
},
btnText:{
    color:"#fff",
    textAlign:'center',
    fontWeight:'500',
    fontFamily:"Arial",
    

},
input:{
  width:300,
  height:45,
  borderStyle:'solid',
  borderColor:"#000",
  borderWidth:1,
  borderRadius:12,
  marginTop:40,
  marginBottom:40,
  padding:10,
  textAlign:"center",
  margin:"auto"
},

caixaBtn:{
  flex:1,
  width:'98%',
  alignItems:'center',
  justifyContent:'space-around',
  flexDirection:'row',
},
caxaTexto:{
  width:300,
  height:40,
  margin:'auto',
  marginBottom:20,
  marginTop:50,
  backgroundColor:'#ccc',
  color:"#fff",
  borderRadius:10,
  textAlign:'center',
  zIndex:1,
},
caxaTexto2:{
  width:'90%',
  height:33,
  margin:'auto',
  marginBottom:20,
  marginTop:80,
  backgroundColor:'#55f21',
  color:"#fff",
  borderRadius:10,
  textAlign:'center',
  zIndex:1,
},
caixaJogador:{
  width:310,
  height:500,
  borderStyle:'solid',
  borderWidth:2,
  borderColor:'#5f6593',
  marginTop:10,
  marginEnd:10,
  borderRadius:10,
  fontFamily:'Arial',
  margin:'auto'
},

caixaNome:{
  width:'100%',
  margin:'auto',
  marginTop:5,
  marginEnd:5,
  padding:10,
  backgroundColor:'#5f6593',
  borderRadius:1,
  fontWeight:"bold",
  color:'#fff',
  textAlign:'center',
  fontSize:20
},

caixaDadosJ:{
  marginTop:10,
  marginEnd:10,
  padding:5,
  fontWeight:'500'
},
caixaimagem:{
  width:'99%',
  height:210,
  margin:'auto',
},
image:{
  width:'100%',
  height:'98%',
  objectFit:'contain',
  borderTopEndRadius:5,
  borderTopLeftRadius:5,
},
imagemBackgroud:{
  width:320,
  height:300,
  margin:'auto',
  marginTop:10,
  marginEnd:10,
  padding:10,
  flex:1,
  justifyContent:'center',
  alignItems:'center',
  alignContent:'center',
  flexDirection:'column',
  objectFit:'contain'
},
caxaF:{
  width:150,
  height:30,
  borderRadius:15
  ,backgroundColor:
  '#daa520',
  textAlign:'center',
  margin:20,
},
a:{
  width:'100%',
  padding:8,
  textAlign:'center'
  
},
modalS:{
  margin:20,
  padding:20,
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
},
modalC:{
  margin:10,
  padding:10,
},
modalBtn:{
    borderWidth:1,
    borderColor:'#45f',
    borderRadius:10
},
modalBtnT:{
  padding:10,
  margin:2,
  color:'#45f',
},
textoModal:{
  padding:10,
  color:"#45f",
  fontSize:21
},
caixaTemp:{
  width:'70%',
  height:40,
  padding:2,
  margin:60,
  backgroundColor:"#45f",
  borderRadius:10,
},
});

